# Generated by Django 2.2.3 on 2019-07-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(verbose_name='Date added')),
                ('referral', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('isJob', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Invoice date')),
                ('total', models.IntegerField()),
                ('isPaid', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(verbose_name='Job start date')),
                ('finish_date', models.DateTimeField(verbose_name='Job finish date')),
                ('active', models.BooleanField()),
                ('address', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Estimate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Invoice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
        ),
    ]
