# Generated by Django 2.2.3 on 2019-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190728_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date added'),
        ),
    ]
