# Generated by Django 2.2.3 on 2019-07-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_job_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customer'),
        ),
    ]
