# Generated by Django 2.2.3 on 2019-08-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190820_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='isJob',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Job'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='Untitled', max_length=250),
        ),
    ]
