# Generated by Django 2.2.3 on 2019-07-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190722_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='add_date',
            field=models.DateTimeField(blank=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
