# Generated by Django 2.2.3 on 2019-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190728_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
