# Generated by Django 2.2.3 on 2019-07-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190731_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
    ]
