# Generated by Django 2.2.3 on 2019-07-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_job_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='newfield',
        ),
    ]
