# Generated by Django 2.2.3 on 2019-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_job_newfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Job start date'),
        ),
    ]
