# Generated by Django 3.0 on 2020-03-16 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200302_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 15), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
