# Generated by Django 3.0 on 2020-03-18 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200316_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 17), null=True),
        ),
    ]
