# Generated by Django 3.0 on 2020-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200318_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
