# Generated by Django 3.0 on 2020-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_job_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unsent'), (1, 'Sent'), (2, 'Overdue'), (3, 'Paid')], null=True),
        ),
    ]
