# Generated by Django 3.0 on 2020-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200519_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
