# Generated by Django 3.0 on 2020-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200519_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
