from django.urls import path 

from main.views import customers, estimates, invoices, jobs, notes, utils, index

urlpatterns = [
	path('', index.get, name='index'),
	path('customers/save', customers.save, name="addCustomer"),
	path('customers/save/<str:id>', customers.save, name="saveCustomer"),
	path('customers/new', customers.new, name="newCustomer"),
	path('customers/all', customers.showAll, name="allCustomers"),
	path('customers/<str:id>', customers.show, name="showCustomer"),
	path('customers/edit/<str:customer_id>', customers.edit, name='editCustomer'),
	path('customers/delete/<str:id>', customers.delete, name='deleteCustomer'),
	path('estimates/all', estimates.showAll, name="allEstimates"),
	path('estimates/new/<str:customer_id>', estimates.new, name="newEstimate"),
	path('estimates/edit/<str:estimate_id>', estimates.edit, name="editEstimate"),
	path('estimates/save', estimates.save, name="saveEstimate"),
	path('estimates/save/<str:estimate_id>', estimates.save, name="saveEstimate"),
	path('estimates/delete/<str:estimate_id>', estimates.delete, name="deleteEstimate"),
	path('estimates/tasks/<str:estimate_id>', estimates.getTasks, name="estimateTasks"),
	path('estimates/<str:estimate_id>', estimates.show, name="showEstimate"),
	path('jobs/all', jobs.showAll, name="allJobs"),
	path('jobs/new/<str:customer_id>', jobs.new, name="newJob"),
	path('jobs/edit/<str:job_id>', jobs.edit, name="editJob"),
	path('jobs/tasks/<str:job_id>', jobs.getTasks, name="jobTasks"),
	path('jobs/save', jobs.save, name="saveJob"),
	path('jobs/save/<str:job_id>', jobs.save, name="saveJob"),
	path('jobs/delete/<str:job_id>', jobs.delete, name="deleteJob"),
	path('jobs/<str:id>', jobs.show, name="showJob"),
	path('invoices/delete/<str:invoice_id>', invoices.delete, name="deleteInvoice"),
	path('invoices/save', invoices.save, name="saveInvoice"),
	path('invoices/save/<str:invoice_id>', invoices.save, name="saveInvoice"),
	path('invoices/update/<str:id>/<str:status>', invoices.update, name="updateInvoice"),
	path('invoices/all', invoices.showAll, name="allInvoices"),
	path('invoices/new/<str:customer_id>', invoices.new, name="newInvoice"),
	path('invoices/edit/<str:invoice_id>', invoices.edit, name="editInvoice"),
	path('invoices/<str:invoice_id>', invoices.show, name="showInvoice"),
	path('addNote', notes.add, name="addNote"),
	path('search/<str:obj_type>/<str:query>', utils.search, name="Search"),
	path('login', utils.loginPage, name="LogInPage"),
	path('auth', utils.auth, name="authenticate"),
	path('logout', utils.log_out, name="log_out"),
]