# Generated by Django 2.2.3 on 2019-08-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190818_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
