from django.urls import path 

from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('addCustomer', views.addCustomer, name="addCustomer"),
	path('findCustomer/<str:query>', views.searchCustomers, name="searchCustomers"),
	path('customers/new', views.newCustomer, name="newCustomer"),
	path('customers/all', views.allCustomers, name="allCustomers"),
	path('customers/<str:id>', views.showCustomer, name="showCustomer"),
	path('estimates/<str:estimate_id>', views.showEstimate, name="showEstimate"),
	path('estimates/new/<str:customer_id>', views.newEstimate, name="newEstimate"),
	path('estimates/edit/<str:estimate_id>', views.editEstimate, name="editEstimate"),
	path('estimates/save', views.saveEstimate, name="saveEstimate"),
	path('jobs/<str:id>', views.showJob, name="showJob"),
	path('jobs/new/<str:customer_id>', views.newJob, name="newJob"),
	path('jobs/edit/<str:job_id>', views.editJob, name="editJob"),
	path('estimatetasks/<str:estimate_id>', views.estimateTasks, name="estimateTasks"),
	path('jobtasks/<str:job_id>', views.jobTasks, name="jobTasks"),
	path('validateJob', views.validateJob, name="validateJob"),
	# path('addJob/<str:customer_id>', views.addJobFromCustomer, name="addJobFromCustomer"),
	# path('addJob/<str:customer_id>/<str:estimate_id>', views.addJobFromEstimate, name="addJobFromEstimate"),
	path('saveJob', views.saveJob, name="saveJob"),
	path('saveJob/<str:job_id>', views.saveJob, name="saveJob"),
	path('saveEstimate', views.saveEstimate, name="saveEstimate"),
	path('saveEstimate/<str:estimate_id>', views.saveEstimate, name="saveEstimate"),
	path('deleteJob/<str:job_id>', views.deleteJob, name="deleteJob"),
	path('deleteEstimate/<str:estimate_id>', views.deleteEstimate, name="deleteEstimate"),
	path('invoices/new/<str:customer_id>', views.newInvoice, name="newInvoice"),
	path('invoices/<str:invoice_id>/edit', views.editInvoice, name="editInvoice"),
	#path('invoices/save', views.saveInvoice, name="saveInvoice"),
	path('invoices/<str:invoice_id>', views.showInvoice, name="showInvoice"),
	path('addNote', views.addNote, name="addNote"),
	path('search/<str:obj_type>/<str:query>', views.search, name="Search"),
	path('saveInvoice', views.saveInvoice, name="saveInvoice"),
	path('saveInvoice/<str:invoice_id>', views.saveInvoice, name="saveInvoice"),
	path('login', views.loginPage, name="LogInPage"),
	path('auth', views.auth, name="authenticate"),
	path('logout', views.log_out, name="log_out"),
]